server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: msvc-clients
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      import-check:
        enabled: false