server:
  port: 8090

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/authDb
    username: root
    password: secret
  jpa:
    show-sql: true
    hibernate:
      # Cambiamos a update para que no elimine los cambios realizados en la BD
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    key:
      private: 3cb00aab337eb28bddbb8f1d737f5250afbfca0b8082d82b4157a6215bfa44e3
    user:
      generator: AUTH0JWT-BACKEND

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka