server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: 'lb://msvc-auth'
          predicates:
            Path=/api/auth/**
        - id: clients
          uri: 'lb://msvc-clients'
          predicates:
            Path=/api/client/**



eureka:
  client:
    register-with-eureka: true