server:
  port: 8090

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3307/authDb}
    username: ${DB_USER:root}
    password: ${DB_PASS:secret}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      # Cambiamos a update para que no elimine los cambios realizados en la BD
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    key:
      private: 3cb00aab337eb28bddbb8f1d737f5250afbfca0b8082d82b4157a6215bfa44e3
    user:
      generator: AUTH0JWT-BACKEND

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}