server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: 'lb://msvc-auth'
          predicates:
            - Path=/api/auth/**
        - id: profile
          uri: 'lb://msvc-auth'
          predicates:
            - Path=/api/profile/**
        - id: clients
          uri: 'lb://msvc-clients'
          predicates:
            - Path=/api/client/**

security:
  jwt:
    key:
      private: 3cb00aab337eb28bddbb8f1d737f5250afbfca0b8082d82b4157a6215bfa44e3
    user:
      generator: AUTH0JWT-BACKEND

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.eureka: DEBUG
