server:
  port: 9090

spring:
  application:
    name: msvc-clients
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ShopClients}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:28_x53-9#fyt}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
