server:
  port: 9090

spring:
  application:
    name: msvc-clients
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-clientes:5433/ShopClients
    username: postgres
    password: 28_x53-9#fyt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: msvc-eureka
  client:
    serviceUrl:
      defaultZone: http://msvc-eureka:8761/eureka
