spring:
  application:
    name: msvc-gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

---

spring:
  config:
    activate:
      on-profile: docker
    config:
      import: optional:configserver:http://msvc-config:8888
